<!-- Product clicks on category product page -->
<script type="text/x-magento-init"> { ".product-item-info" : { "Traverse_Retargeting/js/clickProduct": {} } } </script>

<!-- Cart clicks on cart page -->
<script type="text/x-magento-init"> { "#shopping-cart-table  .actions-toolbar" : { "Traverse_Retargeting/js/clickCart": {} } } </script>
<script type="text/x-magento-init"> { "#form-validate .action.update" : { "Traverse_Retargeting/js/clickCart": {} } } </script>

<script type="text/x-magento-init"> { "*" : { "Traverse_Retargeting/js/loadPage": {} } } </script>
