<?php

?>
<!doctype html>
<html <?= /* @escapeNotVerified */ $htmlAttributes ?>>
    <head <?= /* @escapeNotVerified */ $headAttributes ?>>
<!-- 
        <script src='https://static.traversedlp.com/v1/retargeting.js'></script>
-->
        <script src='http://demo.traverse.cp-m2.com/pub/static/version1519572897/frontend/Magento/luma/en_US/traverseInitTest.js'></script> 
        <?= /* @escapeNotVerified */ $requireJs ?>
        <?= /* @escapeNotVerified */ $headContent ?>
        <?= /* @escapeNotVerified */ $headAdditional ?>
    </head>
    <body data-container="body" data-mage-init='{"loaderAjax": {}, "loader": { "icon": "<?= /* @escapeNotVerified */ $loaderIcon ?>"}}' <?= /* @escapeNotVerified */ $bodyAttributes ?>>
        <?= /* @escapeNotVerified */ $layoutContent ?>
    </body>
</html>
